language: go
go_import_path: github.com/bailantaotao/test-github
sudo: required
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      go: 1.7.x
      script:
        - go test -v $(glide novendor | grep -v "\.\/tests\/\.\.\.")

    - os: linux
      dist: trusty
      sudo: required
      go: 1.8.x
      script:
        - go test -v $(glide novendor | grep -v "\.\/tests\/\.\.\.")

    # These are the latest Go versions.
    - os: linux
      dist: trusty
      sudo: required
      go: 1.9.x
      script:
        - go test -v $(glide novendor | grep -v "\.\/tests\/\.\.\.") 

    - os: osx
      go: 1.9.x
      sudo: required
      script:
        - go test -v $(glide novendor | grep -v "\.\/tests\/\.\.\.")

install:
  - go get github.com/Masterminds/glide